# frozen_string_literal: true

# Serves the pre-rendered static site.
#
# The scorecard, guide, contributors report and rewrite showcases are generated by the scripts in
# scripts/ into dist/, and copied to public/ at build time. Rails hands those files back untouched:
# the pages stay server-rendered, crawlable with JavaScript off, and identical to what nginx served
# before this app existed. Only /test is dynamic.
#
# PAGES is an allowlist keyed by route, never by user input, so no request can reach an arbitrary
# path under public/.
class PagesController < ApplicationController
  PAGES = {
    "scorecard" => "scorecard.html",
    "guide" => "guide.html",
    "check" => "check.html",
    "contributors" => "contributors.html",
    "quality-rewrites" => "quality-rewrites.html",
    "blog-rewrites-review" => "blog-rewrites-review.html"
  }.freeze

  def show
    file = PAGES[params[:page]]
    return head :not_found unless file

    path = Rails.public_path.join(file)
    return head :not_found unless path.exist?

    # HTML must revalidate so a deploy is picked up immediately, matching the old nginx behaviour.
    response.headers["Cache-Control"] = "no-cache"
    send_file path, type: "text/html; charset=utf-8", disposition: "inline"
  end
end
